"""AUREON version — single source of truth for __version__ + banner().

The full behavioral changelog moved to aureon_utils/version_changelog.py
(reference only) to keep this file under the line cap. __version__ / CODENAME /
banner() are byte-identical to before the split.
"""


__version__ = "3.10.2"  # v3.10.2 broker preflight + immediate order-path test: two new bot.py commands. `python bot.py test` (alias `--test`) is a READ-ONLY broker preflight — safe on demo AND real — validating account/terminal/symbol/order-viability/timing + a per-lot risk advisor, with EVERY order probe going through mt5.order_check() ONLY (no order_send/REMOVE/SLTP reachable; grep-proven), aligned console tables + one Discord card, exit 0=READY / nonzero=BLOCKED so a watchdog can gate on it. `python bot.py testfireimmediate` runs the EXACT live placement code (same adapter fns + magic/comment/filling as anchors + RB + SL-modify) for ONE cycle then exits (no watchdog): pending stop -> modify -> cancel -> market@volume_min -> SLTP -> hold>=180s (FundedElite sub-3-min HFT rule) -> close, reporting per-step retcode/latency/intended-vs-actual slippage/filling mode; demo runs flagless, non-demo requires BOTH --i-know-real-account AND --lot-min, refuses if any non-TF_ position is open, aborts+flattens ONLY its own orders on failure. Both place under magic 20260522 + a TF_ comment so their deals are excluded symmetrically from the anchors day-P&L + loss/profit halts exactly like a classic testfire (#125). New tests: tests/test_broker_preflight.py + tests/test_testfireimmediate.py.
# v3.10.1 pending-stop rejection handling (10015 INVALID_PRICE flood fix): preflight (side + broker stops-level) before every stop send; Rogue ENTRY/CHAIN chase-to-market within pending_chase_cap_pts (3.0) else drop the arm; max 3 retries 0.5/1/2s backoff then abandon + one deduped Discord card; anchor/RB legs skip (never chase). Bumped forward from 3.9.1 (absorbs the monster engine + A+C line intended as 3.1.0/3.10.0). Prior 3.9.1: boost_spec_v3 (2026-07-13, flag boost_spec_v3_enabled DEFAULT ON, layered on boost_spec_v2): (1) per-boost-level CONFIRM GATE (IDLE->ARMED->FIRE, B1/B2 independent) -- a break must dwell boost_confirm_dwell_s ($12s) AND extend boost_confirm_ext ($1.50) past its level before entry, a single tick back across the level resets that level only (kills the 07-13 fake-break B1 that stopped -$350); (2) RE-ENTRY INVALIDATION -- a filled boost closes at market the instant price re-enters the band, not at its $10 SL; (3) TRAPPED-LEG CUT -- the first confirmed fire cuts the trapped opposite anchor leg via the existing close path (additive to the -$630 hard loss stop + kill switch, never a substitute; broker SL stays put if the cut rejects; a confirmed cut replaces R7). New PTRACE: BOOST_CONFIRM_ARMED/FAILED, BOOST_INVALIDATED_REENTRY, TRAPPED_CUT (ARMED/FIRE/FAILED/TRAPPED_CUT mirrored to Discord). selftest -> 308 (new 306-308). v3 flag OFF -> v2 immediate-fire byte-identical. (NB: task requested "v3.8.9" but that shipped earlier and HEAD was already 3.9.0 -- bumped forward to 3.9.1.)
CODENAME = "Astra Hawk"


def banner() -> str:
    return f"AUREON v{__version__} ({CODENAME})"